-- Align profile/auth schema with the current application and agent runtime.

alter table public.profiles
  add column if not exists updated_at timestamptz default now(),
  add column if not exists last_active_at timestamptz default now();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    display_name,
    avatar_url,
    xp,
    streak_days,
    current_level,
    last_active_at,
    created_at,
    updated_at
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1), 'Career Explorer'),
    new.raw_user_meta_data ->> 'avatar_url',
    0,
    0,
    1,
    now(),
    now(),
    now()
  )
  on conflict (id) do update
    set display_name = coalesce(public.profiles.display_name, excluded.display_name),
        avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url),
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute procedure public.handle_new_user_profile();

create or replace function public.touch_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.touch_profile_updated_at();

create table if not exists public.agent_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  query text not null,
  status text not null,
  active_agent text not null,
  roadmap_json jsonb not null,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agent_sessions enable row level security;

create policy "Users can view their own agent sessions." on public.agent_sessions
  for select using (auth.uid()::text = user_id);

create policy "Users can insert their own agent sessions." on public.agent_sessions
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update their own agent sessions." on public.agent_sessions
  for update using (auth.uid()::text = user_id);

drop trigger if exists set_agent_sessions_updated_at on public.agent_sessions;
create trigger set_agent_sessions_updated_at
  before update on public.agent_sessions
  for each row execute procedure public.touch_profile_updated_at();

create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  role text not null,
  agent text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agent_events enable row level security;

create policy "Users can view their own agent events." on public.agent_events
  for select using (
    exists (
      select 1 from public.agent_sessions s where s.id = session_id and s.user_id = auth.uid()::text
    )
  );

create policy "Users can insert their own agent events." on public.agent_events
  for insert with check (
    exists (
      select 1 from public.agent_sessions s where s.id = session_id and s.user_id = auth.uid()::text
    )
  );

drop trigger if exists set_agent_events_updated_at on public.agent_events;
create trigger set_agent_events_updated_at
  before update on public.agent_events
  for each row execute procedure public.touch_profile_updated_at();

create table if not exists public.agent_memories (
  id bigint generated by default as identity primary key,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  user_id text not null,
  summary text not null,
  scope text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agent_memories enable row level security;

create policy "Users can view their own agent memories." on public.agent_memories
  for select using (auth.uid()::text = user_id);

create policy "Users can insert their own agent memories." on public.agent_memories
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update their own agent memories." on public.agent_memories
  for update using (auth.uid()::text = user_id);

drop trigger if exists set_agent_memories_updated_at on public.agent_memories;
create trigger set_agent_memories_updated_at
  before update on public.agent_memories
  for each row execute procedure public.touch_profile_updated_at();
