alter table public.profiles
  add column if not exists reading_level text;

create table if not exists public.agent_quizzes (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  user_id text not null,
  question_kind text not null,
  source_agent text not null,
  skill_id text,
  domain_id text,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_option_index integer not null,
  explanation text not null default '',
  focus text not null default '',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_quizzes_correct_option_check check (correct_option_index between 0 and 3)
);

alter table public.agent_quizzes enable row level security;

create policy "Users can view their own agent quizzes." on public.agent_quizzes
  for select using (auth.uid()::text = user_id);

create policy "Users can insert their own agent quizzes." on public.agent_quizzes
  for insert with check (auth.uid()::text = user_id);

create policy "Users can update their own agent quizzes." on public.agent_quizzes
  for update using (auth.uid()::text = user_id);

drop trigger if exists set_agent_quizzes_updated_at on public.agent_quizzes;
create trigger set_agent_quizzes_updated_at
  before update on public.agent_quizzes
  for each row execute procedure public.touch_profile_updated_at();

create table if not exists public.agent_quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id uuid references public.agent_quizzes(id) on delete cascade not null,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  user_id text not null,
  selected_option_index integer not null,
  is_correct boolean not null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint agent_quiz_attempts_selected_option_check check (selected_option_index between 0 and 4)
);

alter table public.agent_quiz_attempts enable row level security;

create policy "Users can view their own agent quiz attempts." on public.agent_quiz_attempts
  for select using (auth.uid()::text = user_id);

create policy "Users can insert their own agent quiz attempts." on public.agent_quiz_attempts
  for insert with check (auth.uid()::text = user_id);
