alter table public.profiles
  add column if not exists reading_level text;

drop table if exists public.agent_quiz_attempts cascade;
drop table if exists public.agent_quizzes cascade;
drop table if exists public.agent_memories cascade;
drop table if exists public.agent_events cascade;
drop table if exists public.agent_sessions cascade;
drop table if exists public.projects cascade;

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  goal text not null,
  roadmap_json jsonb not null,
  status text not null default 'active',
  latest_session_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.projects enable row level security;

create policy "Users can view their own projects." on public.projects
  for select using (auth.uid() = user_id);

create policy "Users can insert their own projects." on public.projects
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own projects." on public.projects
  for update using (auth.uid() = user_id);

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
  before update on public.projects
  for each row execute procedure public.touch_profile_updated_at();

create table public.agent_sessions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  query text not null,
  status text not null,
  active_agent text not null,
  roadmap_json jsonb not null,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agent_sessions enable row level security;

create policy "Users can view their own agent sessions." on public.agent_sessions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own agent sessions." on public.agent_sessions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own agent sessions." on public.agent_sessions
  for update using (auth.uid() = user_id);

drop trigger if exists set_agent_sessions_updated_at on public.agent_sessions;
create trigger set_agent_sessions_updated_at
  before update on public.agent_sessions
  for each row execute procedure public.touch_profile_updated_at();

alter table public.projects
  add constraint projects_latest_session_fk
  foreign key (latest_session_id) references public.agent_sessions(id) on delete set null;

create table public.agent_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  role text not null,
  agent text not null,
  event_type text not null,
  content text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agent_events enable row level security;

create policy "Users can view their own agent events." on public.agent_events
  for select using (
    exists (
      select 1
      from public.agent_sessions s
      where s.id = session_id and s.user_id = auth.uid()
    )
  );

create policy "Users can insert their own agent events." on public.agent_events
  for insert with check (
    exists (
      select 1
      from public.agent_sessions s
      where s.id = session_id and s.user_id = auth.uid()
    )
  );

drop trigger if exists set_agent_events_updated_at on public.agent_events;
create trigger set_agent_events_updated_at
  before update on public.agent_events
  for each row execute procedure public.touch_profile_updated_at();

create table public.agent_memories (
  id bigint generated by default as identity primary key,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  summary text not null,
  scope text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agent_memories enable row level security;

create policy "Users can view their own agent memories." on public.agent_memories
  for select using (auth.uid() = user_id);

create policy "Users can insert their own agent memories." on public.agent_memories
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own agent memories." on public.agent_memories
  for update using (auth.uid() = user_id);

drop trigger if exists set_agent_memories_updated_at on public.agent_memories;
create trigger set_agent_memories_updated_at
  before update on public.agent_memories
  for each row execute procedure public.touch_profile_updated_at();

create table public.agent_quizzes (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  question_kind text not null,
  source_agent text not null,
  skill_id text,
  domain_id text,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_option_index integer not null,
  explanation text not null default '',
  focus text not null default '',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_quizzes_correct_option_check check (correct_option_index between 0 and 3)
);

alter table public.agent_quizzes enable row level security;

create policy "Users can view their own agent quizzes." on public.agent_quizzes
  for select using (auth.uid() = user_id);

create policy "Users can insert their own agent quizzes." on public.agent_quizzes
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own agent quizzes." on public.agent_quizzes
  for update using (auth.uid() = user_id);

drop trigger if exists set_agent_quizzes_updated_at on public.agent_quizzes;
create trigger set_agent_quizzes_updated_at
  before update on public.agent_quizzes
  for each row execute procedure public.touch_profile_updated_at();

create table public.agent_quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id uuid references public.agent_quizzes(id) on delete cascade not null,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  selected_option_index integer not null,
  is_correct boolean not null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint agent_quiz_attempts_selected_option_check check (selected_option_index between 0 and 4)
);

alter table public.agent_quiz_attempts enable row level security;

create policy "Users can view their own agent quiz attempts." on public.agent_quiz_attempts
  for select using (auth.uid() = user_id);

create policy "Users can insert their own agent quiz attempts." on public.agent_quiz_attempts
  for insert with check (auth.uid() = user_id);
