alter table public.agent_quizzes
  add column if not exists project_id uuid references public.projects(id) on delete cascade;

update public.agent_quizzes q
set project_id = s.project_id
from public.agent_sessions s
where s.id = q.session_id
  and q.project_id is null;

alter table public.agent_quiz_attempts
  add column if not exists project_id uuid references public.projects(id) on delete cascade,
  add column if not exists skill_id text,
  add column if not exists posterior_before double precision,
  add column if not exists posterior_after double precision,
  add column if not exists selection_score double precision,
  add column if not exists model_version text;

update public.agent_quiz_attempts a
set
  project_id = s.project_id,
  skill_id = q.skill_id
from public.agent_sessions s,
     public.agent_quizzes q
where s.id = a.session_id
  and q.id = a.quiz_id
  and (a.project_id is null or a.skill_id is null);

create table if not exists public.user_skill_knowledge (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  skill_id text not null,
  domain_id text,
  p_know double precision not null default 0.5,
  p_init double precision not null default 0.5,
  p_learn double precision not null default 0.15,
  p_guess double precision not null default 0.2,
  p_slip double precision not null default 0.1,
  observation_count integer not null default 0,
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  last_quiz_id uuid references public.agent_quizzes(id) on delete set null,
  last_attempt_id bigint references public.agent_quiz_attempts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_skill_knowledge_unique unique (user_id, skill_id),
  constraint user_skill_knowledge_probabilities_check check (
    p_know between 0 and 1 and
    p_init between 0 and 1 and
    p_learn between 0 and 1 and
    p_guess between 0 and 1 and
    p_slip between 0 and 1
  )
);

alter table public.user_skill_knowledge enable row level security;

create policy "Users can view their own user skill knowledge." on public.user_skill_knowledge
  for select using (auth.uid() = user_id);

create policy "Users can insert their own user skill knowledge." on public.user_skill_knowledge
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own user skill knowledge." on public.user_skill_knowledge
  for update using (auth.uid() = user_id);

drop trigger if exists set_user_skill_knowledge_updated_at on public.user_skill_knowledge;
create trigger set_user_skill_knowledge_updated_at
  before update on public.user_skill_knowledge
  for each row execute procedure public.touch_profile_updated_at();

create table if not exists public.project_skill_knowledge (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  skill_id text not null,
  domain_id text,
  p_know double precision not null default 0.5,
  p_init double precision not null default 0.5,
  p_learn double precision not null default 0.15,
  p_guess double precision not null default 0.2,
  p_slip double precision not null default 0.1,
  source_global_updated_at timestamptz,
  observation_count integer not null default 0,
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  last_quiz_id uuid references public.agent_quizzes(id) on delete set null,
  last_attempt_id bigint references public.agent_quiz_attempts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_skill_knowledge_unique unique (project_id, skill_id),
  constraint project_skill_knowledge_probabilities_check check (
    p_know between 0 and 1 and
    p_init between 0 and 1 and
    p_learn between 0 and 1 and
    p_guess between 0 and 1 and
    p_slip between 0 and 1
  )
);

alter table public.project_skill_knowledge enable row level security;

create policy "Users can view their own project skill knowledge." on public.project_skill_knowledge
  for select using (auth.uid() = user_id);

create policy "Users can insert their own project skill knowledge." on public.project_skill_knowledge
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own project skill knowledge." on public.project_skill_knowledge
  for update using (auth.uid() = user_id);

drop trigger if exists set_project_skill_knowledge_updated_at on public.project_skill_knowledge;
create trigger set_project_skill_knowledge_updated_at
  before update on public.project_skill_knowledge
  for each row execute procedure public.touch_profile_updated_at();

create table if not exists public.user_skill_observations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  project_id uuid references public.projects(id) on delete cascade not null,
  session_id uuid references public.agent_sessions(id) on delete cascade not null,
  quiz_id uuid references public.agent_quizzes(id) on delete cascade not null,
  attempt_id bigint references public.agent_quiz_attempts(id) on delete cascade,
  skill_id text not null,
  domain_id text,
  is_correct boolean not null,
  posterior_before double precision not null,
  posterior_after double precision not null,
  selection_reason text not null default '',
  selection_score double precision,
  model_version text not null default 'bkt-skill-v1',
  created_at timestamptz not null default now(),
  constraint user_skill_observations_probabilities_check check (
    posterior_before between 0 and 1 and
    posterior_after between 0 and 1
  )
);

alter table public.user_skill_observations enable row level security;

create policy "Users can view their own user skill observations." on public.user_skill_observations
  for select using (auth.uid() = user_id);

create policy "Users can insert their own user skill observations." on public.user_skill_observations
  for insert with check (auth.uid() = user_id);

create index if not exists idx_agent_quizzes_project_id on public.agent_quizzes(project_id);
create index if not exists idx_agent_quiz_attempts_project_id on public.agent_quiz_attempts(project_id);
create index if not exists idx_agent_quiz_attempts_skill_id on public.agent_quiz_attempts(skill_id);
create index if not exists idx_user_skill_knowledge_user_skill on public.user_skill_knowledge(user_id, skill_id);
create index if not exists idx_project_skill_knowledge_project_skill on public.project_skill_knowledge(project_id, skill_id);
create index if not exists idx_user_skill_observations_project_skill on public.user_skill_observations(project_id, skill_id, created_at desc);
